# Listing 5.7 Displaying the list of files for compilation

tsc --listFiles

# PS D:\drs\TypeScript\GitHub\TypeScript\EssentialTypeScript5\ch05\tools> ..\Listing_5-07.ps1
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es5.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2016.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2017.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2018.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2019.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2020.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2021.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2022.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.dom.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.dom.iterable.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.webworker.importscripts.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.scripthost.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.core.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.collection.d.ts      
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.generator.d.ts       
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.iterable.d.ts        
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.promise.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.proxy.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.reflect.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.symbol.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2016.array.include.d.ts   
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2017.object.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2017.sharedmemory.d.ts    
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2017.string.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2017.intl.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2017.typedarrays.d.ts     
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2018.asyncgenerator.d.ts  
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2018.asynciterable.d.ts   
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2018.intl.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2018.promise.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2018.regexp.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2019.array.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2019.object.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2019.string.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2019.symbol.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2019.intl.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2020.bigint.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2020.date.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2020.promise.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2020.sharedmemory.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2020.string.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2020.symbol.wellknown.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2020.intl.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2020.number.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2021.promise.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2021.string.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2021.weakref.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2021.intl.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2022.array.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2022.error.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2022.intl.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2022.object.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2022.sharedmemory.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2022.string.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2022.regexp.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.decorators.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.decorators.legacy.d.ts
# C:/Users/drste/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2022.full.d.ts
# D:/drs/TypeScript/GitHub/TypeScript/EssentialTypeScript5/ch05/tools/src/index.ts
